version: '3.8'

services:
  backend:
    build: ./example-backend
    image: backend-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend

  frontend:
    build: ./example-frontend
    image: frontend-project
    ports:
      - 5000:5000
    container_name: frontend

  redis:
    image: redis
    container_name: redis
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres